# Generated by Django 4.0.2 on 2022-02-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_account',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='files/pfp'),
        ),
    ]
