# Generated by Django 4.0.2 on 2022-02-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDMS', '0002_user_account_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_account',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/Users/kyletupue/Documents/Ateneo/Project99/P99/Safedrive/static/img/user-default.png', null=True, upload_to='files/pfp'),
        ),
    ]
