# Generated by Django 4.0.2 on 2022-02-23 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SDMS', '0003_alter_user_account_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('address_line_1', models.CharField(max_length=60)),
                ('address_line_2', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=20)),
                ('zip_code', models.IntegerField()),
                ('email_address', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='user_account',
            name='profile_pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='files/pfp'),
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=10)),
                ('truck_classification', models.CharField(max_length=20)),
                ('capacity', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SDMS.company')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SDMS.user_account')),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=50)),
                ('address_line_1', models.CharField(max_length=60)),
                ('address_line_2', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=20)),
                ('zip_code', models.IntegerField()),
                ('distance', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('rate_code', models.IntegerField()),
                ('remarks', models.CharField(max_length=150)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SDMS.company')),
            ],
        ),
        migrations.CreateModel(
            name='Activity_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('activity_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SDMS.user_account')),
            ],
        ),
    ]
