# Generated by Django 4.0.2 on 2022-02-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDMS', '0005_alter_farm_capacity_alter_farm_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='rate_code',
            field=models.IntegerField(),
        ),
    ]
