# Generated by Django 4.0.2 on 2022-02-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDMS', '0006_alter_farm_rate_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
