# Generated by Django 4.0.2 on 2022-02-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDMS', '0007_alter_truck_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='truck_classification',
            field=models.CharField(choices=[('ELF', 'ELF'), ('ONER', 'ONER'), ('FWD', 'FWD'), ('PFWD-1', 'PFWD-1'), ('PFWD-2', 'PFWD-2'), ('SEMI PFWD', 'SEMI PFWD')], default='ELF', max_length=20),
        ),
    ]
