# Generated by Django 4.0.2 on 2022-02-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDMS', '0008_alter_truck_truck_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='truck_classification',
            field=models.CharField(max_length=20),
        ),
    ]
