# Generated by Django 4.0.2 on 2022-03-04 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SDMS', '0009_alter_truck_truck_classification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('ref_num', models.CharField(blank=True, max_length=10, null=True)),
                ('destination', models.CharField(max_length=30)),
                ('trip_date', models.DateField()),
                ('bag_count', models.IntegerField()),
                ('driver_bag', models.IntegerField(default=0)),
                ('helper_1', models.CharField(blank=True, max_length=30, null=True)),
                ('helper_2', models.CharField(blank=True, max_length=30, null=True)),
                ('helper_3', models.CharField(blank=True, max_length=30, null=True)),
                ('helper1_bag', models.IntegerField(default=0)),
                ('helper2_bag', models.IntegerField(default=0)),
                ('helper3_bag', models.IntegerField(default=0)),
                ('additional_expense', models.IntegerField(default=0)),
                ('trip_status', models.CharField(default='SCHEDULED', max_length=20)),
                ('payment_status', models.CharField(default='UNPAID', max_length=20)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SDMS.farm')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SDMS.truck')),
            ],
        ),
    ]
