# Generated by Django 4.0.2 on 2022-03-09 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SDMS', '0010_trips'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='driver_additional',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='truck',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SDMS.company'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SDMS.user_account'),
        ),
    ]
