# Generated by Django 4.0.2 on 2022-03-09 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SDMS', '0011_trips_driver_additional_alter_truck_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trips',
            old_name='driver_bag',
            new_name='driver_basic',
        ),
        migrations.RenameField(
            model_name='trips',
            old_name='helper1_bag',
            new_name='helper1_basic',
        ),
        migrations.RenameField(
            model_name='trips',
            old_name='helper2_bag',
            new_name='helper2_basic',
        ),
        migrations.RenameField(
            model_name='trips',
            old_name='helper3_bag',
            new_name='helper3_basic',
        ),
    ]
