# Generated by Django 4.0.2 on 2022-03-09 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SDMS', '0012_rename_driver_bag_trips_driver_basic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips',
            name='destination',
        ),
    ]
