# Generated by Django 4.0.2 on 2022-03-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDMS', '0013_remove_trips_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='driver_additional',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
