# Generated by Django 4.0.2 on 2022-03-12 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SDMS', '0014_alter_trips_driver_additional'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_account',
            name='accnt_status',
            field=models.CharField(default='OFFLINE', max_length=50),
        ),
        migrations.AlterField(
            model_name='activity_log',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SDMS.user_account'),
        ),
    ]
