# Generated by Django 4.0.2 on 2022-03-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDMS', '0015_user_account_accnt_status_alter_activity_log_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='last_edit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
