# Generated by Django 4.0.2 on 2022-03-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDMS', '0016_trips_last_edit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='additional_expense',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
