# Generated by Django 4.0.2 on 2022-03-15 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SDMS', '0017_alter_trips_additional_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='last_edit_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SDMS.user_account'),
        ),
        migrations.AlterField(
            model_name='trips',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SDMS.farm'),
        ),
        migrations.AlterField(
            model_name='trips',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SDMS.truck'),
        ),
    ]
