# Generated by Django 4.0.2 on 2022-03-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDMS', '0019_trips_create_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='rate_adjustment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
