# Generated by Django 4.0.2 on 2022-03-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDMS', '0020_trips_rate_adjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='management_remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
