# Generated by Django 4.0.2 on 2022-03-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDMS', '0023_client_financialreport_trip_month_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client_financialreport',
            old_name='receivables',
            new_name='base_rate',
        ),
        migrations.AddField(
            model_name='client_financialreport',
            name='rate_adjust',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
