# Generated by Django 4.0.2 on 2022-03-24 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SDMS', '0024_rename_receivables_client_financialreport_base_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='truck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SDMS.truck'),
        ),
    ]
