# Generated by Django 4.0.2 on 2022-04-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDMS', '0025_alter_trips_truck'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='base_rate',
            field=models.IntegerField(default=0),
        ),
    ]
