# Generated by Django 4.0.2 on 2022-04-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDMS', '0026_trips_base_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='base_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
