# Generated by Django 4.0.2 on 2022-04-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDMS', '0027_alter_trips_base_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
