# Generated by Django 4.0.2 on 2022-04-10 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SDMS', '0028_trips_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips',
            name='start_time',
        ),
    ]
