# Generated by Django 4.0.2 on 2022-04-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDMS', '0029_remove_trips_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='billing_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='farm',
            name='billing_rate_override',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='trips',
            name='current_billing_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
