# Generated by Django 4.0.2 on 2022-04-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDMS', '0030_farm_billing_rate_farm_billing_rate_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='driver_additional_remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
