# Generated by Django 4.0.2 on 2022-04-26 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SDMS', '0031_trips_driver_additional_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='billing_rate',
        ),
    ]
