# Generated by Django 4.0.2 on 2022-04-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDMS', '0032_remove_farm_billing_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='driver_additional_remarks',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='management_remarks',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
    ]
