# Generated by Django 4.0.2 on 2022-04-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDMS', '0033_alter_trips_driver_additional_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='additional_expense_remark',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
    ]
